export enum IMAGESTATUS {
	UPLOADED = 'UPLOADED',
	PROCESSING = 'PROCESSING',
	ACCEPTED = 'ACCEPTED',
	REJECTED = 'REJECTED',
	PENDING = 'PENDING',
	FAILED = 'FAILED',
	DUPLICATE = 'DUPLICATE',
	DELETED = 'DELETED'
}